name: CI CD Docker

on:
  push:  # jalakan ketika di push di branch ini
    branches:
      - main
      - master

  pull_request: # jalankan ketika PR di branch ini
    branches:
      - main
      - master

jobs:
  build: # nama job
    runs-on: ubuntu-latest # mesin virtual
    # Build Docker Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # prebuilt action

      - name: Build Docker Image 
        run: docker build -t my-app:${{ github.sha }} .

      - name: Build Success # kalau build success
        run: echo "Docker Image Build Success"
  
  deploy: # nama job
    needs: build
    runs-on: ubuntu-latest # mesin virtual
    if: github.ref == 'refs/heads/master'
    # Build Docker Image
    steps:
      - name: trigger deployment
        run: echo "Deployment Triggered"



